# Generated by Django 5.0 on 2024-03-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_transaction_description_alter_transaction_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
