# Generated by Django 5.0 on 2024-03-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_account_created_at_account_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='updated_at',
        ),
    ]
