# Generated by Django 5.0 on 2024-03-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_remove_entry_created_at_remove_entry_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
