# Generated by Django 5.0 on 2024-04-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_year_end_date_alter_year_start_date'),
        ('ledger', '0008_alter_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.year'),
            preserve_default=False,
        ),
    ]
