# Generated by Django 5.0 on 2024-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_company_address_alter_company_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='company',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='company',
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
