# Generated by Django 5.0 on 2024-06-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_year_end_date_alter_year_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
