# Generated by Django 5.0 on 2024-08-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_year_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='previous',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
