# Generated by Django 5.0 on 2024-03-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("sales", "0004_invoice_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.item",
            ),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
